エラーを確認します。
以下のエラーが発生したので
見てみましょう。samplesizeが0の場合にpltでMIN2とsampleの画像上描画を行います

例外が発生しました: ValueError
Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
  File "C:\projects\seeing\sengiries.py", line 262, in sengiri_X2_justOUTside_edgepoints
    fd_sample = np.abs(np.gradient(sample))
                       ~~~~~~~~~~~^^^^^^^^
  File "C:\projects\seeing\one_or_two_diffDROW.py", line 10, in <module>
    two,one=sengiri_X2_justOUTside_edgepoints(sun_image,limb_wigth=400)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

Co-Authored-By: あおめのいとまごい <mangostin877@gmail.com>