Squashed commit of the following:
commit 5b566c6e705e18cebc8b915ce859295a8551dcdf
Author: fujitenmon-coder <fuji.tenmon@gmail.com>
Date:   Fri May 15 14:10:44 2026 +0900

    解決‼

    エラーの原因は、limbwigthが大きすぎて、samleの外側にはみ出していたことでした。
    急ごしらえで、サンプルが範囲外になっているかを検知するifを追加しました。raiseされます。
    最適なlimb_wigthの計算は作り直したい

    Co-Authored-By: あおめのいとまごい <mangostin877@gmail.com>

commit ffd67622fedb5ae00b0e78067d240f19d0802dbf
Author: fujitenmon-coder <fuji.tenmon@gmail.com>
Date:   Fri May 15 13:44:41 2026 +0900

    エラーを確認します。

    以下のエラーが発生したので
    見てみましょう。samplesizeが0の場合にpltでMIN2とsampleの画像上描画を行います

    例外が発生しました: ValueError
    Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
      File "C:\projects\seeing\sengiries.py", line 262, in sengiri_X2_justOUTside_edgepoints
        fd_sample = np.abs(np.gradient(sample))
                           ~~~~~~~~~~~^^^^^^^^
      File "C:\projects\seeing\one_or_two_diffDROW.py", line 10, in <module>
        two,one=sengiri_X2_justOUTside_edgepoints(sun_image,limb_wigth=400)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

    Co-Authored-By: あおめのいとまごい <mangostin877@gmail.com>