いくつかの修正をした。
１回微分の外側を見るときにfid_dsampleのmaxindexが0になりました()ERRORです。
ちょっとなにが起きてるかわからないので、EROdrowと合体します。

例外が発生しました: ValueError
zero-size array to reduction operation maximum which has no identity
  File "E:\python\tenmon\seeing\sengiries.py", line 252, in sengiri_X2_justOUTside_edgepoints
    index_Max_d_sample = np.where(d_sample == np.max(d_sample))[0][0]#2回微分の最大値
                                              ~~~~~~^^^^^^^^^^
  File "E:\python\tenmon\seeing\one_or_two_diffDROW.py", line 9, in <module>
    two,one=sengiri_X2_justOUTside_edgepoints(sun_image)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity